# Generated by Django 3.2.6 on 2021-08-18 15:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_tag_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='正文必须为MarkDown格式', verbose_name='正文'),
        ),
    ]
